services:
  code-goat-dev:
    container_name: code-goat-dev
    image: code-goat-dev-ubuntu
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/workspace:cached
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroup: host
    stdin_open: true
    tty: true
    privileged: ${IS_PRIVILEGED:-false}
