name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_call:

jobs:
  config:
    name: Configure Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.read.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/platforms.json
          sparse-checkout-cone-mode: false
      
      - name: Read Platform Configuration
        id: read
        run: |
          # Remove comments and trailing commas for valid JSON parsing
          MATRIX_JSON=$(jq -c . .github/platforms.json)
          
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  build:
    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.workflow_runner }}
    
    needs: config
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.config.outputs.matrix) }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/rust
        with:
          target: ${{ matrix.rustup_target }}

      - name: Build Library
        working-directory: ./code-goat
        run: |
          cargo build --release --package code_goat --target ${{ matrix.rustup_target }}
          find . -name "libcode_goat.so"

      - uses: actions/upload-artifact@v4
        with:
          name: code-goat-${{ matrix.name }}
          path: ./code-goat/target/${{ matrix.rustup_target }}/release/libcode_goat.so

  test:
    name: Test (${{ matrix.name }})
    runs-on: ${{ matrix.workflow_runner }}
    
    needs: config
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.config.outputs.matrix) }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/rust
        with:
          target: ${{ matrix.rustup_target }}
      
      - name: Run tests
        working-directory: ./code-goat
        run: |
          # Run all tests that do not require privileged access.
          cargo test --package code_goat --target ${{ matrix.rustup_target }} \
            -- --skip sandbox::tests::mount_sandbox
      
      - name: Run privileged tests
        working-directory: ./code-goat
        run: |
          findmnt -o TARGET,PROPAGATION /
          # It seems like GitHub Actions runners maintain some connections 
          # to a host volume that prevent us from making the root mount private. 
          # As a workaround, we should unmount from the host. Since we cannot use 
          # `mount` operation without `sudo`, we run the test command with it as well.
          sudo unshare --mount --propagation private -- \
            env "PATH=$PATH" \
              "RUSTUP_HOME=$HOME/.rustup" \
              "RUST_BACKTRACE=full" \
            cargo test --package code_goat --target ${{ matrix.rustup_target }} \
              -- sandbox::tests::mount_sandbox