name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_call:

jobs:
  config:
    name: Configure Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.read.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/platforms.json
          sparse-checkout-cone-mode: false
      
      - name: Read Platform Configuration
        id: read
        run: |
          # Remove comments and trailing commas for valid JSON parsing
          MATRIX_JSON=$(jq -c . .github/platforms.json)
          
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  build:
    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.workflow_runner }}
    
    needs: config
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.config.outputs.matrix) }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/rust
        with:
          target: ${{ matrix.rustup_target }}

      - name: Build Library
        working-directory: ./code-goat
        run: |
          cargo build --release --package code_goat --target ${{ matrix.rustup_target }}
          find . -name "libcode_goat.so"

      - uses: actions/upload-artifact@v4
        with:
          name: code-goat-${{ matrix.name }}
          path: ./code-goat/target/${{ matrix.rustup_target }}/release/libcode_goat.so

  test:
    name: Test (${{ matrix.name }})
    runs-on: ${{ matrix.workflow_runner }}
    
    needs: config
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.config.outputs.matrix) }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run tests in Dev Container
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .
          runCmd: |
            cd ./code-goat
            RUST_BACKTRACE=full cargo test --package code_goat --target ${{ matrix.rustup_target }}
